/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import io.packet.test.ErrorPacketTest;
	import io.packet.test.AckPacketTest;
	import io.packet.test.JSONPacketTest;
	import io.packet.test.EventPacketTest;
	import io.packet.test.MessagePacketTest;
	import io.packet.test.HeartbeatPacketTest;
	import io.packet.test.ConnectPacketTest;
	import io.packet.test.DisconnectPacketTest;
	import io.packet.test.PayloadTest;
	
	public class FlexUnitCompilerApplication extends Sprite {
		private var io_packet_test_PayloadTest_obj:io.packet.test.PayloadTest;
		private var io_packet_test_DisconnectPacketTest_obj:io.packet.test.DisconnectPacketTest;
		private var io_packet_test_ConnectPacketTest_obj:io.packet.test.ConnectPacketTest;
		private var io_packet_test_HeartbeatPacketTest_obj:io.packet.test.HeartbeatPacketTest;
		private var io_packet_test_MessagePacketTest_obj:io.packet.test.MessagePacketTest;
		private var io_packet_test_EventPacketTest_obj:io.packet.test.EventPacketTest;
		private var io_packet_test_JSONPacketTest_obj:io.packet.test.JSONPacketTest;
		private var io_packet_test_AckPacketTest_obj:io.packet.test.AckPacketTest;
		private var io_test_PacketFactoryTest_obj:io.packet.test.ErrorPacketTest;
	}
}